Add workaround for VS 2026 internal compiler error
C:\coding\lass\lass\util\smart_ptr_policies.h(560,1): error C1001: Internal compiler error.
4>C:\coding\lass\lass\util\smart_ptr_policies.h(560,1): error C1001: (compiler file 'D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\constexpr\constexpr.cpp', line 9677)
4>C:\coding\lass\lass\util\smart_ptr_policies.h(560,1): error C1001:  To work around this problem, try simplifying or changing the program near the locations listed above.

(cherry picked from commit 86f12d00ba0a9c9421d4c0048dc8ba8559c2cb97)