Replace SafeBool by explicit operator bool
Because of this change, we must use static_bool<bool>(e_predicate) in
LASS_TEST_CHECK, because otherwise, you don't get a boolean context for
the first argument of lass::test::impl::check, and you get the following
error:
error C2664: 'void lass::test::impl::check(bool,const std::string
&,const std::string &,unsigned int)': cannot convert argument 1 from
'TCallback' to 'bool'