Fix C++20 compile-time error in Subprocess
Using MSVC 2022 with C++20, this was giving following error:

error C2280: 'std::basic_ostream<char,std::char_traits<char>> &std::operator <<<std::char_traits<char>>(std::basic_ostream<char,std::char_traits<char>> &,const wchar_t *)': attempting to reference a deleted function

&cmd[0] is const wchar_t* and trying to insert this in a narrow
std::ostream of LASS_ENFORCE_WINAPI clearly doesn't make sense.
Now C++20 finally refuses to compile this.

(cherry picked from commit 2aca0c6768cee9ef83c7f68cd70976c8a4fd84ff)