Fix conanfile libcxx test
The following line:

  if self.settings.compiler.libcxx in {"libstdc++"}

produces following error:

  TypeError: unhashable type: 'SettingsItem'

Using a list instead of a set to contains the possible values works
just as well (performance doesn't matter) and avoids the hash.