Fix issue with missing `__notes__`
The `__notes__` attribute only exists if `add_note` has been used [1].

This fixes following error:

    AttributeError: 'DuplicateError' object has no attribute '__notes__'. Did you mean: '__ne__'?

[1] https://docs.python.org/3/library/exceptions.html#BaseException.__notes__