Fix build error in test_util_callback.cpp
LASS_TEST_CHECK_EQUAL cannot be used to compare two callbacks, because
callbacks cannot be printed to a std::ostream. It results in an error
like this:

error C2678: binary '<<': no operator found which takes a left-hand
operand of type 'std::ofstream' (or there is no acceptable conversion)