Use PUBLIC for lass_LIBS
If we use PRIVATE, then we may end up with errors like this
when building the test_suite (or anything else that depends
on Lass):

undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols:
DSO missing from command line