Restrict support for callables without operator!
Since VS 16.9.1, our trick to support callables without operator! is
broken.

Recall why we needed to support them: C++11 introduced lambda
expressions, which are also callables that can be put in a Lass
Callback, but unlike other callables like say a function pointer, lambda
expressions in Microsoft VC++ did not support operator! until VS 16.2.
i.e. this failed to compile:

  auto a = [](){};
  if (!a) return;

Because of that, I introduced a extra specialisation for callables that
could never be false, by using SFINAE to detect if they support
operator!

template <typename T>
class HasOperatorNot {
    template <typename C> static meta::True test(char[!C()]);
    template <typename C> static meta::False test(...);
public:
    enum { value = sizeof(test<T>(0)) == sizeof(meta::True) };
};

This specialisation would be used by lambda expressions on Microsoft
VC++ until VS 16.2 (after which they supported operator! and they would
start using the normal specialisation, just like on GCC).

Unfortunately, at least since VS 16.9.1 (but not before 16.7.7), the way
to detect operator! support is broken with followign compile-time error:

 error C2131: expression did not evaluate to a constant
 message : a non-constant (sub-)expression was encountered

Because I can't immediately find an alternative method to detect
operator! support, and because VS 16.9.1 is newer than VS 16.2 and thus
this specialisation is not necessary anymore, I've removed this
specialisation if CMake detects lambda expressions support operator!.