Fix pip constraints in test_suite
A typo caused requirements.txt to be reused as constraints so that mypy
version was not fixed. The newly release mypy 1.18.1 caused following
error:

86/87 Test #86: test_python_embedding_mypy .............***Failed
C:\coding\lass\test_suite\test_python_embedding.py:206: error: Argument 1 to "testConstMap" of "Bar" has incompatible type "Mapping[str, str] | None"; expected "Mapping[str, str]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)

(cherry picked from commit ec59ee29ce3636b22645c761266201657d698751)