Replace _PyArg_NoKeywords for Python 3.13
It's no longer available in the public headers [1]

On Linux with GCC 11:

  error: there are no arguments to ‘_PyArg_NoKeywords’ that depend on a template parameter, so a declaration of ‘_PyArg_NoKeywords’ must be available [-fpermissive]
    226 |                 if (!_PyArg_NoKeywords("function", iKw))

[1] https://github.com/python/cpython/issues/110964