Also link Python modules to libpython on Android
On POSIX systems, Python extension modules typically don't link against
libpython as the interpreter already contains all required symbols [1].
However, on Android platforms, that causes following error at import:

  ImportError: dlopen failed: cannot locate symbol "PyExc_TypeError" referenced by "/data/data/com.termux/files/home/liar/build/Release/bin/kernel.cpython-312.so"...

Having the extension modules link against libpython on Android solves
this issue.

[1] https://peps.python.org/pep-0720/#when-should-extensions-be-linked-against-libpython