Fix parsing of std::function methods on termux
std::function can be used to add methods to a Python class using the
PY_CLASS_FREE_METHOD_NAME macro [1]. On termux, however,
lass_stubgen failed to parse these correctly because of the
std::__ndk1 namespace:

  File "/data/data/com.termux/files/home/lass/tools/stubgen/lass_stubgen/parser.py", line 814, in _handle_class_add_method
      assert self_type.name == class_def.cpp_type.name, (
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AssertionError: self type mismatch: std::__ndk1::__wrap_iter<lass::python::NoNone *<lass::util::SharedPtr<lass::test::Spam, , lass::util::DefaultCounter>>>() is not lass::test::ShadowedMemberIteratorContainer.

[1] commit 3a5cb9fda6b4a1a2d69ed4e4df0ca766247cb9a9