Fix lass_stubgen parser for clang >= 20
Fixes following error:

  File "tools/stubgen/lass_stubgen/parser.py", line 157, in parse
    visitor = NodeVisitor(self)
  File "tools/stubgen/lass_stubgen/parser.py", line 1208, in __init__
    self._visitor_cb = cindex.callbacks["cursor_visit"](self.visit_node)
                       ^^^^^^^^^^^^^^^^
  AttributeError: module 'clang.cindex' has no attribute 'callbacks'

And then this one, because they are no longer setting the `errcheck` to
do the type conversion from `CXString` to `str` and rely on explicit
conversion instead [1]:

  File "tools/stubgen/lass_stubgen/parser.py", line 160, in parse
    raise visitor.error
  File "tools/stubgen/lass_stubgen/parser.py", line 1229, in visit_node
    if handler := self._handlers.get(spelling):
                   ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  TypeError: unhashable type

[1] https://github.com/llvm/llvm-project/pull/105490#discussion_r1724776459