Add missing return nullptr in freezeDefinition
After setting a Python exception, the function must not continue.

The missing return didn't seem to have real consequences though. In both
cases we would get the same error message:

```
AssertionError: Parent class Bar of DerivedInnerClass is not frozen yet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_python_embedding.py", line 62, in <module>
    import embedding
ImportError: Failed to import 'embedding'
```

(cherry picked from commit 07aa65c0e7f78318b3ddcdebd90662223571729d)