Support Python 3.15
This fixes following error in test_python_embedding_mypy:

    File ".venv-lass-stubgen-cp315-win_amd64\Lib\site-packages\typing_extensions.py", line 4584, in <module>
      no_type_check_decorator = typing.no_type_check_decorator
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "cpython-3.15.0b2-windows-x86_64-none\Lib\typing.py", line 3940, in __getattr__
      raise AttributeError(f"module {__name__!r} has no attribute {attr!r}")
    AttributeError: module 'typing' has no attribute 'no_type_check_decorator'

(cherry picked from commit 81fb3b741a7b4dd83d9a51fa6e6efd325c7a30a4)