Fix PyExportTraits for complex numbers
Before, PyExportTraits<std::complex<T>> would support infinity or minus
infinity with following errors:

  TypeError: not a float: overflow: inf > 3.40282e+38
  TypeError: not a float: underflow: -inf < -3.40282e+38

This is similar to the old behavior of PyExportTraits for floating point
numbers, and it has the same cause.

The floating point behavior was fixed in commit
dea01c4199933b28fc96b298c4855f2663572ded

In this commit, we also fix the behavior for complex numbers [1,2], and
we finally also support custom complex objects with __complex__ (which
we didn't despite saying so in py_typing_preambl).

By defining LASS_USE_OLD_EXPORTRAITS_COMPLEX=1 (in CMake), you can revert
back to the old behavior.

Note: the above is only true if you passed `complex` arguments to the
complex parameters. If you passed a `float` argument, then internally,
it would use the floating point conversion rules and already behave
correctly unless LASS_USE_OLD_EXPORTRAITS_FLOAT=1 was set. So to have
the old-old behavior, both LASS_USE_OLD_EXPORTRAITS_COMPLEX=1 and
LASS_USE_OLD_EXPORTRAITS_FLOAT=1 must be set.

[1] https://docs.python.org/3.13/c-api/complex.html#c.PyComplex_RealAsDouble
[2] https://docs.python.org/3.13/c-api/complex.html#c.PyComplex_ImagAsDouble