Codify None-to-Py_None behavior for TPyObjPtr
Update documentation to codify existing behavior in
`PyExportTraits<TPyObjPtr>` to translate `None` to `Py_None` instead of
`nullptr`, and add tests.

In contrast to all other pointer-type export traits, getting a
`TPyObjPtr` from a Python `None` object will give you a `Py_None`
pointer, and *not* a `nullptr`!

In all pointer-type export traits, a C++ null pointer is translated to
the Python `None` object, and vice-versa: getting `None` will yield a
null pointer in C++, because `Py_None` is not a valid T pointer.

But the implementation for `TPyObjPtr` deviates from this because
`Py_None` _is_ a valid `PyObject*` pointer, even though `TPyObjPtr` is
just an alias for `util::SharedPtr<PyObject, PyObjectStorage, PyObjectCounter>`.

Returning a nullptr to Python will still yield a None object, just like
for other export traits.

This behavior also affects C++ functions that have `PyObject*`
parameters, as they will use a `TPyObjPtr` as temp value to store the
argument: their arguments will never be null: `None` is passed as
`Py_None`.

This behavior was introduced maybe by accident in 2009 [1], while moving
`PyExportTraits<util::SharedPtr<PyObject, PyObjectStorage, PyObjectCounter>>`
from pyobject_plus.inl to `PyExportTraits<TPyObjPtr>` in
export_traits.h. The if-branch that sets `v` to a null-pointer is
missing a `return 0`, so `v` will always be overwritten by a pointer to
the Python object.

I tried to "fix" it, but that broke `c**2` in the unittest:

  ======================================================================
  ERROR: testNumericOperators (__main__.TestOperators.testNumericOperators)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "lass/test_suite/test_python_embedding.py", line 705, in testNumericOperators
      e = c**2
          ~^^~
  SystemError: NULL object passed to Py_BuildValue

`OverloadLink::call()` decodes the ternary slot's argument into
`TPyObjPtr` and passes it on. With `None` translating to `nullptr`, the
subsequent `Py_BuildValue("(O,O)", ...)` gets a null pointer.

So instead, we've fixed the documentation to formalize the current
behavior.

[1] commit 93deb9630bcdc616913c5f6d792abdcafe722aba