Register Map and Sequence
Register Map as MutableMapping and Sequence as MutableSequence so use
code can use checks like isintance(x, MutableMapping) [1][2].

We don't need to register PyIteratorRange (as Iterator) and
MultiCallback (as Callable) because Iterator and Callable use
__subclasshook__ to test and verify the required methods of an
interface [3][4].

Mypy doesn't accept Callable as second argument of issubclass [5][6],
though it passes at runtime just fine:

  test_suite\test_python_embedding.py:79: error: Argument 2 to "issubclass" has incompatible type "<typing special form>"; expected "_ClassInfo"  [arg-type]

[1] https://docs.python.org/3.13/library/collections.abc.html#
[2] https://docs.python.org/3.13/library/abc.html#abc.ABCMeta.register
[3] https://docs.python.org/3.13/library/collections.abc.html#id18
[4] https://docs.python.org/3.13/library/abc.html#abc.ABCMeta.__subclasshook__
[5] https://github.com/python/mypy/issues/14928
[6] https://github.com/python/mypy/issues/3060